In [4]:
# Checking Numpy version

import numpy as np

print(np.__version__)

1.22.3


In [5]:
# Create a NumPy array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# Use a tuple to create a NumPy array

import numpy as np

a = (1, 2, 3, 4, 5)

arr = np.array(a)

print(arr)

[1 2 3 4 5]


In [8]:
 # Create a 0-D array
 
import numpy as np
arr = np.array(21)
print(arr)

21


In [11]:
# Create a 1-D array

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [12]:
# Create a 2-D array

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
# Create a 3-D array
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [14]:
# Check how many dimensions the arrays have

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [17]:
# Array Indexing

import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[3])

4


In [18]:
# 
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Values: ', arr[1, 1])

Values:  7


In [19]:
# 
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [23]:
# Array Slicing
# Slice elements from index 1 to index 5 from the following array

import numpy as np
arr = np.array([11, 21, 31, 41, 51, 61, 71])
print(arr[1:5])

[21 31 41 51 61 71]


In [24]:
# Slice elements from index 4 to the end of the array

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [14]:
# Slice elements from the beginning to index 4 (not included)

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [25]:
# Return every other element from index 1 to index 5

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [27]:
# Slicing 2-D Array
# From the second element, slice elements from index 1 to index 4 (not included)

import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0, 1:4]) 

[2 3 4]


In [28]:
# 
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [31]:
# Copy 
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [32]:
# View

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [35]:
# Convert the following 1-D array into a 2-D array. reshape(row,column)

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3, 4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
# Convert the following 1-D array into a 3-D array.

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Iterating Arrays

In [41]:
# Iterate on the elements of the following 1-D array

import numpy as np
l=[]
arr = np.array([1, 2, 3,4,5])
for x in arr:
  print(x)
  l.append(x)
print(l)

1
2
3
4
5
[1, 2, 3, 4, 5]


In [44]:
# Iterate on the elements of the following 2-D array
import numpy as np
l= []
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)
  l.append(x)
print(l)

[1 2 3]
[4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]


In [46]:
# Iterate on each scalar element of the 2-D array

import numpy as np
l=[]
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)
    l.append(y)
print(l)

1
2
3
4
5
6
[1, 2, 3, 4, 5, 6]


In [27]:
# 3-D Array
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [47]:
# Each Element

import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [48]:
# Iterating Arrays Using nditer()

import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


Joining NumPy Arrays

In [53]:
# Join two arrays

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5])
arr = np.concatenate((arr1, arr2))


print(arr)

[1 2 3 4 5]


In [55]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = (arr1+ arr2)

print(arr)

[5 7 9]


In [56]:
# Join two 2-D arrays along rows (axis=1)

import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [60]:
# Joining Arrays Using Stack Functions

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [61]:
# NumPy provides a helper function: hstack() to stack along rows

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [62]:
# NumPy provides a helper function: vstack()  to stack along columns

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [63]:
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


Splitting NumPy Arrays

In [66]:
# Split the array in 3 parts - numpy.array_split(numpy Array , how many value..)

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6,9,5])
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2, 3]), array([4, 5, 6]), array([9, 5])]


In [67]:
# Access the splitted arrays

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [68]:
# Split the 2-D array into three 2-D arrays

import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [69]:
# Use the hsplit() method to split the 2-D array into three 2-D arrays along rows

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


Sorting Arrays

In [40]:
# The NumPy ndarray object has a function called sort(), that will sort a specified array.

import numpy as np
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


Random Numbers in NumPy

In [82]:
# Generate a random integer from 0 to 100f
from numpy import random

x = random.randint(1020)

print(x)

288


In [87]:
# The random module's rand() method returns a random float between 0 and 1.
from numpy import random

x = random.rand()

print(x)

0.6041203871976819


In [95]:
# The randint() method takes a size parameter where you can specify the shape of an array.
# Generate a 1-D array containing 5 random integers from 0 to 100.

from numpy import random

x=random.randint(100, size=(3))

print(x)

[31 56 24]


In [103]:
# Random 2-D Array

from numpy import random

x = random.randint(100, size=(2, 2))

print(x)

[[74 93]
 [39 61]]


In [108]:
# The rand() method also allows you to specify the shape of the array.
# Generate a 1-D array containing 5 random floats

from numpy import random
x = random.rand(2)

print(x)

[0.13865478 0.92838036]


In [54]:
# The choice() method allows you to generate a random value based on an array of values.
# The choice() method takes an array as a parameter and randomly returns one of the values.

# Return one of the values in an array

from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

5


In [55]:
# Find the HCF of the following two numbers:

import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [56]:
# Find the GCD for all of the numbers in the following array:

import numpy as np

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


In [57]:
# Find the LCM of the following two numbers:

import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [58]:
# Find the LCM of the values of the following array:

import numpy as np

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [59]:
# Convert following array with repeated elements to a set:

import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [60]:
# Find sine value of PI/2:

import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0
